name: Build pipeline

on: [push]

env:
  AUTH_SERVER_URL: ${{secrets.AUTH_SERVER_URL}}
  JWT_ISSUER_URI: ${{secrets.JWT_ISSUER_URI}}
  KEYCLOAK_ADMIN_PASSWORD: ${{secrets.KEYCLOAK_ADMIN_PASSWORD}}
  KEYCLOAK_ADMIN_USERNAME: ${{secrets.KEYCLOAK_ADMIN_USERNAME}}
  KEYCLOAK_CLIENT_ID: ${{secrets.KEYCLOAK_CLIENT_ID}}
  KEYCLOAK_CLIENT_SECRET: ${{secrets.KEYCLOAK_CLIENT_SECRET}}
  KEYCLOAK_CLIENT_UUID: ${{secrets.KEYCLOAK_CLIENT_UUID}}
  KEYCLOAK_CREDENTIALS_SECRET: ${{secrets.KEYCLOAK_CREDENTIALS_SECRET}}
  KEYCLOAK_REALM: ${{secrets.KEYCLOAK_REALM}}
  KEYCLOAK_RESOURCE: ${{secrets.KEYCLOAK_RESOURCE}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Compile the code
        run: mvn compile

      - name: Run tests
        run: mvn test